### ISSUE TITLE
Normalisation(combine) throws when inheriting from element with own children

### ISSUE THREAD

**Issue by plastikfan** [plastikfan/jaxom-ts#41]
This issue was discovered as a result of improving test code coverage. The following is an example of the case that causes an exception:
```
<?xml version="1.0"?>
  <Application name="pez">
    <Cli>
      <Commands>
        <Command name="base-command" abstract="true">
          <AlphaChild rank="alpha"/>
        </Command>
        <Command name="list-command" inherits="base-command">
          <BetaChild rank="beta"/>
        </Command>
      </Commands>
    </Cli>
  </Application>
```
which throws:

     TypeError: reduce: list must be array or iterable
      at _reduce (/Users/Plastikfan/dev/github/js/jaxom-ts/node_modules/ramda/src/internal/_reduce.js:60:9)
      at reduceBy (/Users/Plastikfan/dev/github/js/jaxom-ts/node_modules/ramda/src/reduceBy.js:55:10)
      at /Users/Plastikfan/dev/github/js/jaxom-ts/node_modules/ramda/src/internal/_dispatchable.js:41:15
      at /Users/Plastikfan/dev/github/js/jaxom-ts/node_modules/ramda/src/internal/_curryN.js:37:27
      at /Users/Plastikfan/dev/github/js/jaxom-ts/node_modules/ramda/src/internal/_arity.js:14:19
      at /Users/Plastikfan/dev/github/js/jaxom-ts/node_modules/ramda/src/internal/_checkForMethod.js:22:72
      at /Users/Plastikfan/dev/github/js/jaxom-ts/node_modules/ramda/src/internal/_curry2.js:22:18
      at f1 (/Users/Plastikfan/dev/github/js/jaxom-ts/node_modules/ramda/src/internal/_curry1.js:18:17)
      at Normaliser.combineDescendants (/Users/Plastikfan/dev/github/js/jaxom-ts/lib/normaliser/normaliser.class.ts:50:51)

caused by this line (of normaliser.combineDescendants):

const renameGroupByElementChildrenObj = groupByElement(children);

**Comment by plastikfan** [comment]
combineDescendants needs to be looked at again; in particular reduceByChildren seems wrong because valud is an array, but we're trying to index into it with a string (value[descendantsLabel]) like its an object.

**Comment by plastikfan** [comment]
Also need to write a test with mult- level normalisation, from grand-parent to grand-child (as opposed to just parent/child).

**Comment by plastikfan** [comment]
This issue is caused by the the fact that an inherited item may already have been normalised at the time of building local children at which point the local children have not yet been normalised so we have a clash in form between inherited and local children. The inherited children is a normalised map and the local children is still an array.

A possible solution would be to denormalise the inherited item which should just be renormalised again after the local children and been fully built.

**Comment by plastikfan** [comment]
Denormalisation is the solution implemented.

**Comment by plastikfan** [comment]
The current implementation of combineDescendants is breaking the normalisation model. All normalisation should be done via the id attribute and nothing else. combineDescendants is transforming elements and creating an object structure where the Element name is the key. This is wrong.

combineDescendants has to resolve this scenario:

```XML
<?xml version="1.0"?>
      <Application name="pez">
        <Cli>
          <Commands>
            <Command name="duo-command" abstract="true">
              <Arguments>
                <ArgumentRef name="from"/>
                <ArgumentRef name="to"/>
              </Arguments>
              <ArgumentGroups>
                <Implies>
                  <ArgumentRef name="from"/>
                  <ArgumentRef name="to"/>
                </Implies>
              </ArgumentGroups>
            </Command>
            <Command name="test" describe="Test regular expression definitions" inherits="duo-command">
              <Arguments>
                <ArgumentRef name="config"/>
                <ArgumentRef name="expr"/>
                <ArgumentRef name="input"/>
              </Arguments>
              <ArgumentGroups>
                <Implies>
                  <ArgumentRef name="input"/>
                  <ArgumentRef name="expr"/>
                  <ArgumentRef name="input"/>
                </Implies>
              </ArgumentGroups>
            </Command>
          </Commands>
        </Cli>
      </Application>
```

... which create this json (without combine being active)

```Javascript
{
            name: 'test',
            _: 'Command',
            _children: [
              {
                _: 'Arguments',
                _children: [
                  { name: 'config', _: 'ArgumentRef' },
                  { name: 'expr', _: 'ArgumentRef' },
                  { name: 'input', _: 'ArgumentRef' }
                ]
              },
              {
                _: 'ArgumentGroups',
                _children: [
                  {
                    _: 'Implies',
                    _children: [
                      { name: 'input', _: 'ArgumentRef' },
                      { name: 'expr', _: 'ArgumentRef' },
                      { name: 'input', _: 'ArgumentRef' }
                    ]
                  }
                ]
              },
              {
                _: 'Arguments',
                _children: [
                  { name: 'from', _: 'ArgumentRef' },
                  { name: 'to', _: 'ArgumentRef' }
                ]
              },
              {
                _: 'ArgumentGroups',
                _children: [
                  {
                    _: 'Implies',
                    _children: [
                      { name: 'from', _: 'ArgumentRef' },
                      { name: 'to', _: 'ArgumentRef' }
                    ]
                  }
                ]
              }
            ],
            describe: 'Test regular expression definitions'
          }
```

ie, Elements of the same should be collected together, without breaking normalisation model.

**Comment by plastikfan** [comment]
Combining descendants is applicable depending on the Element in question but this is a client issue. From the example above, Arguments and ArgumentGroups can be combined ok, but Implies should not be. Assuming we have an option to specify if an Element can be combined (Arguments.combine = true, ArgumentGroups.combine = true, Implies.combine=false), the result should look like this:

```XML
{
            name: 'test',
            _: 'Command',
            _children: [
              {
                //
                _: 'Arguments',
                _children: [
                  { name: 'from', _: 'ArgumentRef' },
                  { name: 'to', _: 'ArgumentRef' },
                  { name: 'config', _: 'ArgumentRef' },
                  { name: 'expr', _: 'ArgumentRef' },
                  { name: 'input', _: 'ArgumentRef' },
                  { name: 'config', _: 'ArgumentRef' },
                  { name: 'expr', _: 'ArgumentRef' },
                  { name: 'input', _: 'ArgumentRef' }
                ]
              },
              {
                _: 'ArgumentGroups',
                _children: [
                  {
                    _: 'Implies',
                    _children: [
                      { name: 'from', _: 'ArgumentRef' },
                      { name: 'to', _: 'ArgumentRef' }
                    ]
                  },
                  {
                    _: 'Implies',
                    _children: [
                      { name: 'input', _: 'ArgumentRef' },
                      { name: 'expr', _: 'ArgumentRef' },
                      { name: 'input', _: 'ArgumentRef' }
                    ]
                  }
                ]
              }
            ],
            describe: 'Test regular expression definitions'
          }
```

**Comment by plastikfan** [comment]
AN addenum to the previous comment, Implies isn't actually afflicted with this issue, but Arguments and ArgumentGroups are. The reason is when command inherits, the items it inherits have their own descendants, some of which may be of the same type; Arguments and ArgumentGropus. Implies is self contaned inside ArgumentGroups and is only implicity inherited not explicit.

So to proceed from here, we don't need any element level config. We just need to combine the descendants of inherited items, but still conform to the existing model where noramlisation is by id attribute, and don't accidently noramlise by another concept as is currently the case with Element name.
